# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3042f70fefa355e4520ddeb2d219fb3a456468f5090f7942e4728b1d546e10f7907242284a464c99344516e4f5a18022060b7233ce6fd96a90441c0fbb684ba8

test:
  secret_key_base: 6e943f00f9b81bd194f7d362753e1c8a07fbfd5bd1dcf68a1dc50d82867742baa3e4b39369f18cd129d6c7b0cf959152b01139a7a503a5b1f75be72bb46c1ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
